export const AskTime: string[] = [
  '.hora',
  '.HORA',
  'a que hora son?',
  'a que hora son',
  'A que hora son?',
  'A que hora son',
  'a qué hora son?',
  'a qué hora son',
  'A qué hora son?',
  'A qué hora son',
  'hora',
  'HORA',
  'a que horas son?',
  'a que horas son',
  'A que horas son?',
  'A que horas son',
  'a qué horas son?',
  'a qué horas son',
  'A qué horas son?',
  'A qué horas son',
];
export const AskDate: string[] = [
  '.fecha',
  '.FECHA',
  '.dia',
  '.DIA',
  'que dia es?',
  'que dia es',
  'que dia es?',
  '.DIA',
  '.dia',
  'Que dia es',
  'Qué dia es?',
  'Qué dia es',
  'Qué dia es?',
  'Qué dia es',
  'Dia',
  'dia',
  'Que dia es?',
  'Que dia es',
  'Que dia es?',
  'que dia es',
  'qué dia es?',
  'qué dia es',
  'Día',
  '.DÍA',
  'DIA',
  'Qué dia es?',
  'Qué dia es',
  '.fecha',
  '.FECHA',
  '.día',
  '.DÍA',
  'que día es?',
  'que día es',
  'que día es?',
  'Que día es',
  'Qué día es?',
  'Qué día es',
  'Qué día es?',
  'Qué día es',
  'día',
  'día',
  'Que día es?',
  'Que día es',
  'Que día es?',
  'que día es',
  'qué día es?',
  'qué día es',
  'Qué día es?',
  'Qué día es',
];
export const Greeting: string[] = [
  'como estas',
  'Como estas',
  'Como estas?',
  'como estas?',
  'comotas',
  'Comotas',
  'como tas',
  'Como tas',
  'como tas?',
  'Como tas?',
  'Comotas?',
];
export const ConfusingMsg: Array<string> = [
  'No entendi eso :c',
  'Nope',
  'No hablo muy bien español aun',
  'Perdoname porfavoooor! No entendi eso',
  'Soy tan torpe en el español que no entendi lo que dijiste, perdanme:(',
  'No entendi eso, perdon',
];
export const GreetingMessage: Array<string> = [
  'Hola',
  'Buenass',
  'Como estas?',
  'Holap :p',
];
export const TimeMsg: Array<string> = [
  '¡Hora de empezar la funcion!',
  'Hora de comer... Para mi, tu tambien lo deberias hacer',
  'Vaya... La hora ideal para hacer grandes cosas',
  'LLego la hora...',
  'A esta hora se cumplen los sueños',
  '¡No lo pienses mas!',
];
export const DateMsg: Array<string> = [
  'Este dia es lo maximo',
  'Aun queda por hacer de este un grandioso dia',
  'Otro dia, otra moneda',
  'Animo',
  'Parece que es un gran dia',
];
