[package]
name = "echobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferrisgram = "0.1.5"
tokio = "1.21.2"
